.TH "BST BUILD" "1" "21-Jun-2017" "" "bst build Manual"
.SH NAME
bst\-build \- Build elements in a pipeline
.SH SYNOPSIS
.B bst build
[OPTIONS] TARGET
.SH DESCRIPTION
Build elements in a pipeline
.SH OPTIONS
.TP
\fB\-\-all\fP
Build elements that would not be needed for the current build plan
.TP
\fB\-\-track\fP
Track new source references before building (implies --all)
.TP
\fB\-a,\fP \-\-arch TEXT
The target architecture (default: x86_64)
.TP
\fB\-\-variant\fP TEXT
A variant of the specified target