.TH "BST ARTIFACT LIST-CONTENTS" "1" "2025-05-09" "2.5" "bst artifact list-contents Manual"
.SH NAME
bst\-artifact\-list-contents \- List the contents of an artifact
.SH SYNOPSIS
.B bst artifact list-contents
[OPTIONS] [ARTIFACTS]...
.SH DESCRIPTION
List the contents of an artifact.
.PP
    Note that 'artifacts' can be element names, which must end in '.bst',
    or artifact references, which must be in the format `<project_name>/<element>/<key>`.
    
.SH OPTIONS
.TP
\fB\-l,\fP \-\-long
Provide more information about the contents of the artifact.
