.TH "BST ARTIFACT SHOW" "1" "2020-10-14" "" "bst artifact show Manual"
.SH NAME
bst\-artifact\-show \- Show the cached state of artifacts
.SH SYNOPSIS
.B bst artifact show
[OPTIONS] [ARTIFACTS]...
.SH DESCRIPTION
show the cached state of artifacts
.SH OPTIONS
.TP
\fB\-d,\fP \-\-deps [build|run|all|none]
The dependencies we also want to show  [default: none]
