.TH "BST TRACK" "1" "21-Jun-2017" "" "bst track Manual"
.SH NAME
bst\-track \- Track new source references
.SH SYNOPSIS
.B bst track
[OPTIONS] TARGET
.SH DESCRIPTION
Consults the specified tracking branches for new versions available
to build and updates the project with any newly available references.

By default this will track sources for all dependencies of the specified
target element.

Specify `--deps` to control which sources to track:


    none:  No dependencies, just the element itself
    all:   All dependencies
.SH OPTIONS
.TP
\fB\-\-except\fP TEXT
Except certain dependencies from tracking
.TP
\fB\-d,\fP \-\-deps [none|all]
The dependencies to track (default: all)
.TP
\fB\-a,\fP \-\-arch TEXT
The target architecture (default: x86_64)
.TP
\fB\-\-variant\fP TEXT
A variant of the specified target