.TH "BST SOURCE CHECKOUT" "1" "2025-05-09" "2.5" "bst source checkout Manual"
.SH NAME
bst\-source\-checkout \- Checkout sources of an element
.SH SYNOPSIS
.B bst source checkout
[OPTIONS] [ELEMENT]
.SH DESCRIPTION
Checkout sources of an element to the specified location
.PP
    When this command is executed from a workspace directory, the default
    is to checkout the sources of the workspace element.
    
.SH OPTIONS
.TP
\fB\-f,\fP \-\-force
Allow files to be overwritten
.TP
\fB\-\-except\fP PATH
Except certain dependencies
.TP
\fB\-d,\fP \-\-deps [build|none|run|all]
The dependencies whose sources to checkout  [default: none]
.TP
\fB\-\-tar\fP LOCATION
Create a tarball containing the sources instead of a file tree.
.TP
\fB\-\-compression\fP [gz|xz|bz2]
The compression option of the tarball created.
.TP
\fB\-\-include\-build\-scripts\fP
.PP
.TP
\fB\-\-directory\fP DIRECTORY
The directory to checkout the sources to
.TP
\fB\-\-source\-remote\fP REMOTE
A remote for downloading cached sources
.TP
\fB\-\-ignore\-project\-source\-remotes\fP
Ignore remote source cache servers recommended by projects
