.TH "BST WORKSPACE RESET" "1" "19-Feb-2018" "" "bst workspace reset Manual"
.SH NAME
bst\-workspace\-reset \- Reset a workspace to its original state
.SH SYNOPSIS
.B bst workspace reset
[OPTIONS] ELEMENT
.SH DESCRIPTION
Reset a workspace to its original state
.SH OPTIONS
.TP
\fB\-\-track\fP
Track and fetch the latest source before resetting
.TP
\fB\-\-no\-checkout\fP
Do not checkout the source, only link to the given directory