.TH "BST ARTIFACT LOG" "1" "2025-05-09" "2.5" "bst artifact log Manual"
.SH NAME
bst\-artifact\-log \- Show logs of artifacts
.SH SYNOPSIS
.B bst artifact log
[OPTIONS] [ARTIFACTS]...
.SH DESCRIPTION
Show build logs of artifacts
.SH OPTIONS
.TP
\fB\-\-out\fP PATH
Output logs to individual files in the specified path. If absent, logs are written to stdout.
