.TH "BST ARTIFACT" "1" "12-Feb-2019" "" "bst artifact Manual"
.SH NAME
bst\-artifact \- Manipulate cached artifacts
.SH SYNOPSIS
.B bst artifact
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manipulate cached artifacts
.SH COMMANDS
.PP
\fBcheckout\fP
  Checkout contents of an artifact
  See \fBbst artifact-checkout(1)\fP for full documentation on the \fBcheckout\fP command.
.PP
\fBpull\fP
  Pull a built artifact
  See \fBbst artifact-pull(1)\fP for full documentation on the \fBpull\fP command.
.PP
\fBpush\fP
  Push a built artifact
  See \fBbst artifact-push(1)\fP for full documentation on the \fBpush\fP command.
.PP
\fBlog\fP
  Show logs of an artifact
  See \fBbst artifact-log(1)\fP for full documentation on the \fBlog\fP command.
