.TH "BST WORKSPACE CLOSE" "1" "25-Mar-2018" "" "bst workspace close Manual"
.SH NAME
bst\-workspace\-close \- Close a workspace
.SH SYNOPSIS
.B bst workspace close
[OPTIONS] ELEMENT
.SH DESCRIPTION
Close a workspace
.SH OPTIONS
.TP
\fB\-\-remove\-dir\fP
Remove the path that contains the closed workspace