.TH "BST SOURCE" "1" "2025-05-09" "2.5" "bst source Manual"
.SH NAME
bst\-source \- Manipulate sources for an element
.SH SYNOPSIS
.B bst source
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manipulate sources for an element
.SH COMMANDS
.PP
\fBfetch\fP
  Fetch sources in a pipeline
  See \fBbst source-fetch(1)\fP for full documentation on the \fBfetch\fP command.
.PP
\fBpush\fP
  Push sources in a pipeline
  See \fBbst source-push(1)\fP for full documentation on the \fBpush\fP command.
.PP
\fBtrack\fP
  Track new source references
  See \fBbst source-track(1)\fP for full documentation on the \fBtrack\fP command.
.PP
\fBcheckout\fP
  Checkout sources of an element
  See \fBbst source-checkout(1)\fP for full documentation on the \fBcheckout\fP command.
