.TH "BST SOURCE TRACK" "1" "2025-05-09" "2.5" "bst source track Manual"
.SH NAME
bst\-source\-track \- Track new source references
.SH SYNOPSIS
.B bst source track
[OPTIONS] [ELEMENTS]...
.SH DESCRIPTION
Consults the specified tracking branches for new versions available
    to build and updates the project with any newly available references.
.PP
    Specifying no elements will result in tracking the default targets
    of the project. If no default targets are configured, all project
    elements will be tracked.
.PP
    When this command is executed from a workspace directory, the default
    is to track the workspace element.
.PP
    If no default is declared, all elements in the project will be tracked
.PP
    By default this will track just the specified element, but you can also
    update a whole tree of dependencies in one go.
.PP
    Specify `--deps` to control which sources to track:
.PP
    
        none:  No dependencies, just the specified elements
        all:   All dependencies of all specified elements
    
.SH OPTIONS
.TP
\fB\-\-except\fP PATH
Except certain dependencies from tracking
.TP
\fB\-d,\fP \-\-deps [build|run|all|none]
The dependencies to track  [default: none]
.TP
\fB\-J,\fP \-\-cross\-junctions
Allow crossing junction boundaries
