.TH "BST PUSH" "1" "15-Jan-2018" "" "bst push Manual"
.SH NAME
bst\-push \- Push a built artifact
.SH SYNOPSIS
.B bst push
[OPTIONS] [ELEMENTS]...
.SH DESCRIPTION
Push a built artifact to the configured remote artifact cache.

Specify `--deps` to control which artifacts to push:


    none:  No dependencies, just the element itself
    all:   All dependencies
.SH OPTIONS
.TP
\fB\-d,\fP \-\-deps [none|all]
The dependencies to push (default: none)