.TH "BST SOURCE-BUNDLE" "1" "14-Jul-2019" "" "bst source-bundle Manual"
.SH NAME
bst\-source-bundle \- Produce a build bundle to be manually executed
.SH SYNOPSIS
.B bst source-bundle
[OPTIONS] ELEMENT
.SH DESCRIPTION
Produce a source bundle to be manually executed
    
.SH OPTIONS
.TP
\fB\-\-except\fP PATH
Elements to except from the tarball
.TP
\fB\-\-compression\fP [none|gz|bz2|xz]
Compress the tar file using the given algorithm.
.TP
\fB\-\-track\fP
Track new source references before bundling
.TP
\fB\-f,\fP \-\-force
Overwrite an existing tarball
.TP
\fB\-\-directory\fP TEXT
The directory to write the tarball to
