.TH "BST PUSH" "1" "14-Jul-2019" "" "bst push Manual"
.SH NAME
bst\-push \- Push a built artifact
.SH SYNOPSIS
.B bst push
[OPTIONS] [ELEMENTS]...
.SH DESCRIPTION
Push a built artifact to a remote artifact cache.
.PP
The default destination is the highest priority configured cache. You can
override this by passing a different cache URL with the `--remote` flag.
.PP
Specify `--deps` to control which artifacts to push:
.PP

    none:  No dependencies, just the element itself
    all:   All dependencies
.SH OPTIONS
.TP
\fB\-d,\fP \-\-deps [none|all]
The dependencies to push (default: none)
.TP
\fB\-r,\fP \-\-remote TEXT
The URL of the remote cache (defaults to the first configured cache)
