.TH "BST ARTIFACT DELETE" "1" "2020-10-14" "" "bst artifact delete Manual"
.SH NAME
bst\-artifact\-delete \- Remove artifacts from the local cache
.SH SYNOPSIS
.B bst artifact delete
[OPTIONS] [ARTIFACTS]...
.SH DESCRIPTION
Remove artifacts from the local cache
.SH OPTIONS
.TP
\fB\-d,\fP \-\-deps [none|run|build|all]
The dependencies to delete  [default: none]
