.TH "BST WORKSPACE OPEN" "1" "10-Sep-2017" "" "bst workspace open Manual"
.SH NAME
bst\-workspace\-open \- Open a new workspace
.SH SYNOPSIS
.B bst workspace open
[OPTIONS] ELEMENT DIRECTORY
.SH DESCRIPTION
Open a workspace for manual source modification
.SH OPTIONS
.TP
\fB\-\-no\-checkout\fP
Do not checkout the source, only link to the given directory
.TP
\fB\-f,\fP \-\-force
Overwrite files existing in checkout directory
.TP
\fB\-s,\fP \-\-source INDEX
The source to create a workspace for. Projects with one source may omit this
.TP
\fB\-\-variant\fP TEXT
A variant of the specified target
.TP
\fB\-\-track\fP
Track and fetch new source references before checking out the workspace