.TH "BST CHECKOUT" "1" "10-Jul-2017" "" "bst checkout Manual"
.SH NAME
bst\-checkout \- Checkout a built artifact
.SH SYNOPSIS
.B bst checkout
[OPTIONS] TARGET DIRECTORY
.SH DESCRIPTION
Checkout a built artifact to the specified directory
    
.SH OPTIONS
.TP
\fB\-f,\fP \-\-force
Overwrite files existing in checkout directory
.TP
\fB\-a,\fP \-\-arch TEXT
Architecture of the machine running the build (default: x86_64)
.TP
\fB\-\-host\-arch\fP TEXT
Run as a native build for the given architecture (defaults to --arch)
.TP
\fB\-\-target\-arch\fP TEXT
Produce elements that execute on this architecture (defaults to --arch)
.TP
\fB\-\-variant\fP TEXT
A variant of the specified target