.TH "BST PULL" "1" "15-Jan-2018" "" "bst pull Manual"
.SH NAME
bst\-pull \- Pull a built artifact
.SH SYNOPSIS
.B bst pull
[OPTIONS] [ELEMENTS]...
.SH DESCRIPTION
Pull a built artifact from the configured remote artifact cache.

Specify `--deps` to control which artifacts to pull:


    none:  No dependencies, just the element itself
    all:   All dependencies
.SH OPTIONS
.TP
\fB\-d,\fP \-\-deps [none|all]
The dependency artifacts to pull (default: none)