.TH "BST PUSH" "1" "22-Jan-2019" "" "bst push Manual"
.SH NAME
bst\-push \- Push a built artifact
.SH SYNOPSIS
.B bst push
[OPTIONS] [ELEMENTS]...
.SH OPTIONS
.TP
\fB\-d,\fP \-\-deps [none|all]
The dependencies to push (default: none)
.TP
\fB\-r,\fP \-\-remote TEXT
The URL of the remote cache (defaults to the first configured cache)