.TH "BST WORKSPACE CLOSE" "1" "2020-10-14" "" "bst workspace close Manual"
.SH NAME
bst\-workspace\-close \- Close workspaces
.SH SYNOPSIS
.B bst workspace close
[OPTIONS] [ELEMENTS]...
.SH DESCRIPTION
Close a workspace
.SH OPTIONS
.TP
\fB\-\-remove\-dir\fP
Remove the path that contains the closed workspace
.TP
\fB\-a,\fP \-\-all
Close all open workspaces
