.TH "BST ARTIFACT DELETE" "1" "14-Jul-2019" "" "bst artifact delete Manual"
.SH NAME
bst\-artifact\-delete \- Remove artifacts from the local cache
.SH SYNOPSIS
.B bst artifact delete
[OPTIONS] [ARTIFACTS]...
.SH DESCRIPTION
Remove artifacts from the local cache
.SH OPTIONS
.TP
\fB\-\-no\-prune\fP
Do not prune the local cache of unreachable refs
