.TH "BST SOURCE PUSH" "1" "2025-05-09" "2.5" "bst source push Manual"
.SH NAME
bst\-source\-push \- Push sources in a pipeline
.SH SYNOPSIS
.B bst source push
[OPTIONS] [ELEMENTS]...
.SH DESCRIPTION
Push sources required to build the pipeline
.PP
    Specifying no elements will result in pushing the sources of the default
    targets of the project. If no default targets are configured, sources of
    all project elements will be pushed.
.PP
    When this command is executed from a workspace directory, the default
    is to push the sources of the workspace element.
.PP
    By default this will only try to push sources for the specified
    elements.
.PP
    Specify `--deps` to control which sources to fetch:
.PP
    
        none:  No dependencies, just the element itself
        run:   Runtime dependencies, including the element itself
        build: Build time dependencies, excluding the element itself
        all:   All dependencies
    
.SH OPTIONS
.TP
\fB\-\-except\fP PATH
Except certain dependencies from pushing
.TP
\fB\-d,\fP \-\-deps [none|build|run|all]
The dependencies to push  [default: none]
.TP
\fB\-\-source\-remote\fP REMOTE
A remote for uploading sources
.TP
\fB\-\-ignore\-project\-source\-remotes\fP
Ignore remote source cache servers recommended by projects
