.TH "BST INIT" "1" "2025-05-09" "2.5" "bst init Manual"
.SH NAME
bst\-init \- Initialize a new BuildStream project
.SH SYNOPSIS
.B bst init
[OPTIONS] [TARGET_DIRECTORY]
.SH DESCRIPTION
Initialize a new BuildStream project
.PP
    Creates a new BuildStream project.conf in the project
    directory.
.PP
    Unless `--project-name` is specified, this will be an
    interactive session.
    
.SH OPTIONS
.TP
\fB\-\-project\-name\fP TEXT
The project name to use
.TP
\fB\-\-min\-version\fP TEXT
The required format version  [default: 2.4]
.TP
\fB\-\-element\-path\fP PATH
The subdirectory to store elements in  [default: elements]
.TP
\fB\-f,\fP \-\-force
Allow overwriting an existing project.conf
