.TH "BST INIT" "1" "14-Jul-2019" "" "bst init Manual"
.SH NAME
bst\-init \- Initialize a new BuildStream project
.SH SYNOPSIS
.B bst init
[OPTIONS]
.SH DESCRIPTION
Initialize a new BuildStream project
.PP
Creates a new BuildStream project.conf in the project
directory.
.PP
Unless `--project-name` is specified, this will be an
interactive session.
.SH OPTIONS
.TP
\fB\-\-project\-name\fP TEXT
The project name to use
.TP
\fB\-\-format\-version\fP INTEGER
The required format version (default: 12)
.TP
\fB\-\-element\-path\fP PATH
The subdirectory to store elements in (default: elements)
.TP
\fB\-f,\fP \-\-force
Allow overwriting an existing project.conf
