.TH "BST PULL" "1" "14-Jul-2019" "" "bst pull Manual"
.SH NAME
bst\-pull \- Pull a built artifact
.SH SYNOPSIS
.B bst pull
[OPTIONS] [ELEMENTS]...
.SH DESCRIPTION
Pull a built artifact from the configured remote artifact cache.
.PP
By default the artifact will be pulled one of the configured caches
if possible, following the usual priority order. If the `--remote` flag
is given, only the specified cache will be queried.
.PP
Specify `--deps` to control which artifacts to pull:
.PP

    none:  No dependencies, just the element itself
    all:   All dependencies
.SH OPTIONS
.TP
\fB\-d,\fP \-\-deps [none|all]
The dependency artifacts to pull (default: none)
.TP
\fB\-r,\fP \-\-remote TEXT
The URL of the remote cache (defaults to the first configured cache)
