.TH "BST FETCH" "1" "27-May-2017" "" "bst fetch Manual"
.SH NAME
bst\-fetch \- Fetch sources in a pipeline
.SH SYNOPSIS
.B bst fetch
[OPTIONS] TARGET
.SH DESCRIPTION
Fetch sources in a pipeline
.SH OPTIONS
.TP
\fB\-d,\fP \-\-deps [none|plan|all|build|run]
Specify a dependency scope to fetch (default: none)
.TP
\fB\-a,\fP \-\-arch TEXT
The target architecture (default: x86_64)
.TP
\fB\-\-variant\fP TEXT
A variant of the specified target