.TH "BST WORKSPACE CLOSE" "1" "27-Jul-2017" "" "bst workspace close Manual"
.SH NAME
bst\-workspace\-close \- Close a workspace
.SH SYNOPSIS
.B bst workspace close
[OPTIONS] ELEMENT
.SH DESCRIPTION
Close a workspace
.SH OPTIONS
.TP
\fB\-s,\fP \-\-source TEXT
The source of the workspace to remove. Projects with one source may omit this
.TP
\fB\-\-remove\-dir\fP
Remove the path that contains the closed workspace
.TP
\fB\-\-variant\fP TEXT
A variant of the specified target