.TH "BST CHECKOUT" "1" "26-Apr-2018" "" "bst checkout Manual"
.SH NAME
bst\-checkout \- Checkout a built artifact
.SH SYNOPSIS
.B bst checkout
[OPTIONS] ELEMENT DIRECTORY
.SH DESCRIPTION
Checkout a built artifact to the specified directory
    
.SH OPTIONS
.TP
\fB\-f,\fP \-\-force
Overwrite files existing in checkout directory
.TP
\fB\-f,\fP \-\-deps
The dependencies to checkout (default: run)
.TP
\fB\-\-integrate\fP / \-\-no\-integrate
Whether to run integration commands
.TP
\fB\-\-hardlinks\fP
Checkout hardlinks instead of copies (handle with care)
