.TH "BST WORKSPACE" "1" "2020-10-14" "" "bst workspace Manual"
.SH NAME
bst\-workspace \- Manipulate developer workspaces
.SH SYNOPSIS
.B bst workspace
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manipulate developer workspaces
.SH COMMANDS
.PP
\fBopen\fP
  Open a new workspace
  See \fBbst workspace-open(1)\fP for full documentation on the \fBopen\fP command.
.PP
\fBclose\fP
  Close workspaces
  See \fBbst workspace-close(1)\fP for full documentation on the \fBclose\fP command.
.PP
\fBreset\fP
  Reset a workspace to its original state
  See \fBbst workspace-reset(1)\fP for full documentation on the \fBreset\fP command.
.PP
\fBlist\fP
  List open workspaces
  See \fBbst workspace-list(1)\fP for full documentation on the \fBlist\fP command.
