.TH "BST-ARTIFACT-RECEIVE" "1" "06-Mar-2018" "" "bst-artifact-receive Manual"
.SH NAME
bst-artifact-receive \- Receive pushed artifacts over ssh
.SH SYNOPSIS
.B bst-artifact-receive
[OPTIONS] REPO
.SH DESCRIPTION
A BuildStream sister program for receiving artifacts send to a shared artifact cache
    
.SH OPTIONS
.TP
\fB\-v,\fP \-\-verbose
Verbose mode
.TP
\fB\-d,\fP \-\-debug
Debug mode
.TP
\fB\-\-pull\-url\fP TEXT
Clients who try to pull over SSH will be redirected here  [required]