kind: stack
description: |

  This is the main entry point including cases in the cache key test.

depends:
- sources/local1.bst
- sources/local2.bst
- sources/remote1.bst
- sources/remote2.bst
- sources/tar1.bst
- sources/tar2.bst
- elements/build1.bst
- elements/build2.bst
- elements/build3.bst
- elements/compose1.bst
- elements/compose2.bst
- elements/compose3.bst
- elements/compose4.bst
- elements/compose5.bst
- elements/import1.bst
- elements/import2.bst
- elements/import3.bst
- elements/script1.bst
- elements/sort0.bst
- elements/sort1.bst
- elements/sort2.bst
- elements/sort3.bst
- elements/sort4.bst
- elements/sort5.bst
- elements/sort6.bst
- elements/sort7.bst
- elements/sort8.bst
- elements/sort9.bst
- elements/variables1.bst
