kind: stack
description: |

  This is the main entry point including cases in the cache key test.

depends:
- sources/bzr1.bst
- sources/git1.bst
- sources/git2.bst
- sources/local1.bst
- sources/local2.bst
- sources/ostree1.bst
- sources/patch1.bst
- sources/patch2.bst
- sources/patch3.bst
- sources/pip1.bst
- sources/tar1.bst
- sources/tar2.bst
- sources/zip1.bst
- sources/zip2.bst
- elements/build1.bst
- elements/build2.bst
- elements/compose1.bst
- elements/compose2.bst
- elements/compose3.bst
- elements/compose4.bst
- elements/compose5.bst
- elements/import1.bst
- elements/import2.bst
- elements/import3.bst
- elements/script1.bst
