# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from buildstream._protos.buildstream.v2 import source_pb2 as buildstream_dot_v2_dot_source__pb2


class SourceServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSource = channel.unary_unary(
        '/buildstream.v2.SourceService/GetSource',
        request_serializer=buildstream_dot_v2_dot_source__pb2.GetSourceRequest.SerializeToString,
        response_deserializer=buildstream_dot_v2_dot_source__pb2.Source.FromString,
        )
    self.UpdateSource = channel.unary_unary(
        '/buildstream.v2.SourceService/UpdateSource',
        request_serializer=buildstream_dot_v2_dot_source__pb2.UpdateSourceRequest.SerializeToString,
        response_deserializer=buildstream_dot_v2_dot_source__pb2.Source.FromString,
        )


class SourceServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSource(self, request, context):
    """Retrieve a source message given a reference name from the service

    Errors:
    * `NOT_FOUND`: The requested reference is not in the cache.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSource(self, request, context):
    """Sets a source message on the service

    Errors:
    * `RESOURCE_EXHAUSTED`: There is insufficient storage space to add the
    entry to the cache.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SourceServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSource': grpc.unary_unary_rpc_method_handler(
          servicer.GetSource,
          request_deserializer=buildstream_dot_v2_dot_source__pb2.GetSourceRequest.FromString,
          response_serializer=buildstream_dot_v2_dot_source__pb2.Source.SerializeToString,
      ),
      'UpdateSource': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSource,
          request_deserializer=buildstream_dot_v2_dot_source__pb2.UpdateSourceRequest.FromString,
          response_serializer=buildstream_dot_v2_dot_source__pb2.Source.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'buildstream.v2.SourceService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
