kind: import

sources:
- kind: tar
  url: https://flying-ponies.com/releases/1.2/pony-flight-1.2.3.tgz
  ref: 9d0c936c78d0dfe3a67cae372c9a2330476ea87a2eec16b2daada64a664ca501
  provenance:
    attribution-text: We ackowledge that flying ponies are very real
    concluded-license: flying-ponies-V2
    copyright-text: Please do not steal our flying ponies
    declared-license: flying-ponies-V2
    description: Flying ponies, what more do you want?
    external-reference: OTHER flying.ponies ponies.can.fly:believe_it
    homepage: https://flying-ponies.com/index.html
    issue-tracker: https://bugs.flying-ponies.com/issues
    name: flying-ponies
    originator: Flying Pony Equestrian Centre
