# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buildstream/v2/buildstream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buildstream._protos.build.bazel.remote.execution.v2 import remote_execution_pb2 as build_dot_bazel_dot_remote_dot_execution_dot_v2_dot_remote__execution__pb2
from buildstream._protos.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n buildstream/v2/buildstream.proto\x12\x0e\x62uildstream.v2\x1a\x36\x62uild/bazel/remote/execution/v2/remote_execution.proto\x1a\x1cgoogle/api/annotations.proto\"9\n\x13GetReferenceRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"O\n\x14GetReferenceResponse\x12\x37\n\x06\x64igest\x18\x01 \x01(\x0b\x32\'.build.bazel.remote.execution.v2.Digest\"v\n\x16UpdateReferenceRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\t\x12\x37\n\x06\x64igest\x18\x03 \x01(\x0b\x32\'.build.bazel.remote.execution.v2.Digest\"\x19\n\x17UpdateReferenceResponse\"&\n\rStatusRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\"\'\n\x0eStatusResponse\x12\x15\n\rallow_updates\x18\x01 \x01(\x08\x32\xca\x03\n\x10ReferenceStorage\x12\x90\x01\n\x0cGetReference\x12#.buildstream.v2.GetReferenceRequest\x1a$.buildstream.v2.GetReferenceResponse\"5\x82\xd3\xe4\x93\x02/\x12-/v2/{instance_name=**}/buildstream/refs/{key}\x12\xa1\x01\n\x0fUpdateReference\x12&.buildstream.v2.UpdateReferenceRequest\x1a\'.buildstream.v2.UpdateReferenceResponse\"=\x82\xd3\xe4\x93\x02\x37\x1a-/v2/{instance_name=**}/buildstream/refs/{key}:\x06\x64igest\x12\x7f\n\x06Status\x12\x1d.buildstream.v2.StatusRequest\x1a\x1e.buildstream.v2.StatusResponse\"6\x82\xd3\xe4\x93\x02\x30\x1a./v2/{instance_name=**}/buildstream/refs:statusb\x06proto3')



_GETREFERENCEREQUEST = DESCRIPTOR.message_types_by_name['GetReferenceRequest']
_GETREFERENCERESPONSE = DESCRIPTOR.message_types_by_name['GetReferenceResponse']
_UPDATEREFERENCEREQUEST = DESCRIPTOR.message_types_by_name['UpdateReferenceRequest']
_UPDATEREFERENCERESPONSE = DESCRIPTOR.message_types_by_name['UpdateReferenceResponse']
_STATUSREQUEST = DESCRIPTOR.message_types_by_name['StatusRequest']
_STATUSRESPONSE = DESCRIPTOR.message_types_by_name['StatusResponse']
GetReferenceRequest = _reflection.GeneratedProtocolMessageType('GetReferenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREFERENCEREQUEST,
  '__module__' : 'buildstream.v2.buildstream_pb2'
  # @@protoc_insertion_point(class_scope:buildstream.v2.GetReferenceRequest)
  })
_sym_db.RegisterMessage(GetReferenceRequest)

GetReferenceResponse = _reflection.GeneratedProtocolMessageType('GetReferenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETREFERENCERESPONSE,
  '__module__' : 'buildstream.v2.buildstream_pb2'
  # @@protoc_insertion_point(class_scope:buildstream.v2.GetReferenceResponse)
  })
_sym_db.RegisterMessage(GetReferenceResponse)

UpdateReferenceRequest = _reflection.GeneratedProtocolMessageType('UpdateReferenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREFERENCEREQUEST,
  '__module__' : 'buildstream.v2.buildstream_pb2'
  # @@protoc_insertion_point(class_scope:buildstream.v2.UpdateReferenceRequest)
  })
_sym_db.RegisterMessage(UpdateReferenceRequest)

UpdateReferenceResponse = _reflection.GeneratedProtocolMessageType('UpdateReferenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREFERENCERESPONSE,
  '__module__' : 'buildstream.v2.buildstream_pb2'
  # @@protoc_insertion_point(class_scope:buildstream.v2.UpdateReferenceResponse)
  })
_sym_db.RegisterMessage(UpdateReferenceResponse)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATUSREQUEST,
  '__module__' : 'buildstream.v2.buildstream_pb2'
  # @@protoc_insertion_point(class_scope:buildstream.v2.StatusRequest)
  })
_sym_db.RegisterMessage(StatusRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'buildstream.v2.buildstream_pb2'
  # @@protoc_insertion_point(class_scope:buildstream.v2.StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)

_REFERENCESTORAGE = DESCRIPTOR.services_by_name['ReferenceStorage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REFERENCESTORAGE.methods_by_name['GetReference']._options = None
  _REFERENCESTORAGE.methods_by_name['GetReference']._serialized_options = b'\202\323\344\223\002/\022-/v2/{instance_name=**}/buildstream/refs/{key}'
  _REFERENCESTORAGE.methods_by_name['UpdateReference']._options = None
  _REFERENCESTORAGE.methods_by_name['UpdateReference']._serialized_options = b'\202\323\344\223\0027\032-/v2/{instance_name=**}/buildstream/refs/{key}:\006digest'
  _REFERENCESTORAGE.methods_by_name['Status']._options = None
  _REFERENCESTORAGE.methods_by_name['Status']._serialized_options = b'\202\323\344\223\0020\032./v2/{instance_name=**}/buildstream/refs:status'
  _GETREFERENCEREQUEST._serialized_start=138
  _GETREFERENCEREQUEST._serialized_end=195
  _GETREFERENCERESPONSE._serialized_start=197
  _GETREFERENCERESPONSE._serialized_end=276
  _UPDATEREFERENCEREQUEST._serialized_start=278
  _UPDATEREFERENCEREQUEST._serialized_end=396
  _UPDATEREFERENCERESPONSE._serialized_start=398
  _UPDATEREFERENCERESPONSE._serialized_end=423
  _STATUSREQUEST._serialized_start=425
  _STATUSREQUEST._serialized_end=463
  _STATUSRESPONSE._serialized_start=465
  _STATUSRESPONSE._serialized_end=504
  _REFERENCESTORAGE._serialized_start=507
  _REFERENCESTORAGE._serialized_end=965
# @@protoc_insertion_point(module_scope)
